# Generated by Django 2.0.6 on 2021-09-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevMenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillos',
            name='imagen',
            field=models.URLField(default='https://i.pinimg.com/originals/e7/ee/13/e7ee13eacea7dea62f085b59b240b0b0.png', max_length=8000),
        ),
    ]
