# Generated by Django 2.0.6 on 2021-10-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevMenu', '0002_platillos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillos',
            name='imagen',
            field=models.URLField(default='https://i.pinimg.com/originals/e7/ee/13/e7ee13eacea7dea62f085b59b240b0b0.png', max_length=80),
        ),
    ]
